# Generated by cucumber-sinatra. (2015-02-18 17:19:39 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/hello_world.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Hello_world

class Hello_worldWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Hello_worldWorld.new
end
